backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "about"
    label: "About Me"
    files:
      - file: "about.json"
        label: "About Content"
        name: "about"
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Paragraph 1", name: "para1", widget: "text" }
          - { label: "Paragraph 2", name: "para2", widget: "text" }

  - name: "featured"
    label: "Featured Work"
    files:
      - file: "featured.json"
        label: "Featured Projects"
        name: "featured"
        fields:
          - label: "Projects"
            name: "projects"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
