backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "about"
    label: "About Me"
    files:
      - file: "about.json"
        label: "About Content"
        name: "about"
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Paragraph 1", name: "para1", widget: "text" }
          - { label: "Paragraph 2", name: "para2", widget: "text" }

  - name: "featured"
    label: "Featured Work"
    delete: true
    files:
      - file: "featured.json"
        label: "Featured Projects"
        name: "featured"
        fields:
          - label: "Projects"
            name: "projects"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Link", name: "link", widget: "string" }

  - name: "testimonials"
    label: "Client Love"
    files:
      - file: "testimonials.json"
        label: "Client Testimonials"
        name: "testimonials"
        delete: true
        fields:
          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            fields:
              - { label: "Quote", name: "quote", widget: "text" }
              - { label: "Name", name: "name", widget: "string" }

  - name: "reactions"
    label: "Client Reactions"
    delete: true
    files:
      - file: "reactions.json"
        label: "Client Reactions"
        name: "reactions"
        fields:
          - label: "Reactions"
            name: "reactions"
            widget: "list"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Text", name: "text", widget: "string" }
