backend:
  name: git-gateway
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "about"
    label: "About Me"
    files:
      - file: "content/about.yml"
        label: "About Section"
        name: "about"
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Paragraph 1", name: "para1", widget: "text" }
          - { label: "Paragraph 2", name: "para2", widget: "text" }

  - name: "work"
    label: "Featured Work"
    folder: "content/work"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "URL", name: "url", widget: "string" }

  - name: "testimonials"
    label: "Testimonials"
    file: "content/testimonials.yml"
    fields:
      - label: "Testimonials"
        name: "testimonials"
        widget: "list"
        fields:
          - { label: "Quote", name: "quote", widget: "text" }
          - { label: "Name", name: "name", widget: "string" }

  - name: "reactions"
    label: "Client Reactions"
    file: "content/reactions.yml"
    fields:
      - label: "Reactions"
        name: "reactions"
        widget: "list"
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Reaction", name: "reaction", widget: "string" }
